### ISSUE TITLE
Crash on difficulty value "0": Floating Point Exception

### ISSUE THREAD

**Issue by ejv2** [ejv2/Maths-Challenge-Quiz#3]
## Describe the bug
If the user provides the value "0" as their difficulty, the game will crash while attempting to generate questions.

## To Reproduce
1. Build the game normally with default compile flags/constants
2. Start the game normally with no flags
3. Provide a zero when you are prompted for the difficulty value
4. Wait for any round other than division
5. The game will crash, citing an error related to floating point logic

## Expected behavior
Practice mode is enabled and question generation succeeds as normal

## Screenshots
![Terminal screenshot of crash](https://i.imgur.com/UUYX7yV.png)

## System information
 - OS: Artix Linux 64-bit
 - Terminal emulator: ST
 - Build: From source on the dev branch

## Additional context
Could this have anything to do with divide by zero errors? If the individual rounds are incorrectly detecting when practice mode is enabled, they could try and use it in regular RNG calculations, which would be bad.

**Comment by ethanv2** [comment]
I've written a basic patch. At some point, I want to clean this up by using the actual compile constant, improve the logic to be a bit more robust etc.

For now, this will do. This will ship in the next release.
